options = 
{
	{ 
		default = 9,
		label = "Survival: Build Time", 
		help = "Length of initial building time.", 
		key = 'opt_Survival_BuildTime', 
		pref = 'opt_Survival_BuildTime', 
		values = { 
			{text = "0:00",help = "", key = 0, },
			{text = "0:30",help = "", key = 30, }, 
			{text = "1:00",help = "", key = 60, }, 
			{text = "1:30",help = "", key = 90, }, 
			{text = "2:00",help = "", key = 120, }, 
			{text = "2:30",help = "", key = 150, }, 
			{text = "3:00",help = "", key = 180, }, 
			{text = "4:00",help = "", key = 240, }, 
			{text = "5:00",help = "", key = 300, },
			{text = "6:00",help = "", key = 360, }, 
			{text = "7:00",help = "", key = 420, }, 
			{text = "8:00",help = "", key = 480, }, 
			{text = "9:00",help = "", key = 540, }, 
			{text = "10:00",help = "", key = 600, }, 
		}, 
	},
	{ 
		default = 12,
		label = "Survival: Difficulty", 
		help = "How many enemies attack each minute (per player).", 
		key = 'opt_Survival_EnemiesPerMinute', 
		pref = 'opt_Survival_EnemiesPerMinute', 
		values = {
			{text = "4",help = "", key = 4, },
			{text = "6",help = "", key = 6, },
			{text = "8",help = "", key = 8, },
			{text = "12",help = "", key = 12, },
			{text = "16 (Easy)",help = "", key = 16, },
			{text = "20",help = "", key = 20, },
			{text = "22",help = "", key = 22, },
			{text = "24",help = "", key = 24, },
			{text = "26",help = "", key = 26, },
			{text = "28",help = "", key = 28, },
			{text = "30",help = "", key = 30, },
			{text = "32 (challenging)",help = "", key = 32, },
			{text = "34",help = "", key = 34, },
			{text = "36",help = "", key = 36, },
			{text = "40",help = "", key = 40, },
			{text = "42",help = "", key = 42, },
			{text = "48",help = "", key = 48, },
			{text = "56",help = "", key = 56, }, 
			{text = "64",help = "", key = 64, }, 
			{text = "72",help = "", key = 72, },
			{text = "80 (Insanity)",help = "", key = 80, },
			{text = "96",help = "", key = 96, },
			{text = "128",help = "", key = 128, },
			{text = "Over 9000",help = "", key = 9001, },
		},
	},
	{ 
		default = 1, 
		label = "Survival: Wave Frequency", 
		help = "How long between waves.", 
		key = 'opt_Survival_WaveFrequency', 
		pref = 'opt_Survival_WaveFrequency', 
		values = { 
			{text = "Streaming",help = "", key = 10, }, 
			{text = "1:00 - Fast Waves",help = "", key = 60, }, 
			{text = "2:00 - Normal Waves",help = "", key = 120, }, 
			{text = "3:00 - Huge Waves",help = "", key = 180, }, 
			{text = "4:00 - Epic Waves",help = "", key = 240, }, 
		},
	},
	{
		default = 6,
		label = "Survival: Objective Health",
		help = "Health of the defence objective (the building in the center of the map)",
		key = 'opt_CenterObjectiveHealth',
		pref = 'opt_CenterObjectiveHealth',
		values = {
			{ text = "Do not sneeze", help = "1 HP", key = 1, },
			{ text = "Do not sneeze too hard", help = "100 HP", key = 100, },
			{ text = "1000 HP", help = "Can sneeze once", key = 1000, },
			{ text = "2000 HP", help = "Can sneeze twice", key = 2000, },
			{ text = "4000 HP", help = "Can sneeze a bunch of times", key = 4000, },
			{ text = "5000 HP", help = "Classical HP with 4 players", key = 5000, },
			{ text = "6000 HP", help = "A little extra", key = 6000, },
			{ text = "7500 HP", help = "A little more extra", key = 7500, },
			{ text = "10000 HP", help = "Over 9000", key = 10000, },
			{ text = "25000 HP", help = "XXXL", key = 25000, },
			{ text = "100000 HP", help = "Bitcoins 2020 price", key = 100000, },
			{ text = "1000000 HP", help = "Bitcoins 2021 price", key = 1000000, },
		}
	},
	{
		default = 7,
		label = "Survival: Objective Regen",
		help = "Regeneration rate of the defence objective (the building in the center of the map)",
		key = 'opt_CenterObjectiveRegen',
		pref = 'opt_CenterObjectiveRegen',
		values = {
			{ text = "None", help = "No regeneration", key = 0, },
			{ text = "2 hp/s", help = "", key = 2, },
			{ text = "5 hp/s", help = "", key = 5, },
			{ text = "10 hp/s", help = "", key = 10, },
			{ text = "15 hp/s", help = "", key = 15, },
			{ text = "20 hp/s", help = "", key = 20, },
			{ text = "25 hp/s", help = "", key = 25, },
			{ text = "30 hp/s", help = "", key = 30, },
			{ text = "35 hp/s", help = "", key = 35, },
			{ text = "50 hp/s", help = "", key = 50, },
			{ text = "75 hp/s", help = "", key = 75, },
			{ text = "100 hp/s", help = "", key = 100, },
			{ text = "150 hp/s", help = "", key = 150, },
			{ text = "1000 hp/s", help = "", key = 1000, },
		}
	},
	{
		default = 6,
		label = "Survival: Objective Vision",
		help = "How much vision the defence objective should give",
		key = 'opt_CenterObjectiveVision',
		pref = 'opt_CenterObjectiveVision',
		values = {
			{ text = "Disabled", help = "No extra vision granted", key = 0, },
			{ text = "100", help = "Allows you to see your own base. Very useful!", key = 100, },
			{ text = "150", help = "Till the gaps", key = 150, },
			{ text = "200", help = "A bit in front of the defences", key = 200, },
			{ text = "250", help = "Only the corners are dark", key = 250, },
			{ text = "350", help = "The whole map", key = 350, },
		}
	},
	{
		default = 3,
		label = "Survival: Energy bonus",
		help = "Each player get this amount of bonus power",
		key = 'opt_CenterBonusEnergy',
		pref = 'opt_CenterBonusEnergy',
		values = {
			{ text = "Disabled", help = "No extra energy", key = 0, },
			{ text = "50", help = "Each player gets 50 extra energy income (via overflow)", key = 50, },
			{ text = "100", help = "Each player gets 100 extra energy income (via overflow)", key = 100, },
			{ text = "200", help = "Each player gets 200 extra energy income (via overflow)", key = 200, },
			{ text = "500", help = "Each player gets 5000 extra energy income (via overflow)", key = 500, },
			{ text = "1000", help = "Each player gets 1000 extra energy income (via overflow)", key = 1000, },
		}
	},
	{
		default = 1,
		label = "Survival: Auto Reclaim",
		help = "If enabled, when you kill a survival unit it will not leave a wreck, and you will get a fraction of its mass and energy cost",
		key = 'opt_CenterAutoReclaim',
		pref = 'opt_CenterAutoReclaim',
		values = {
			{ text = "Disabled (Wreckages On)", help = "Disabled", key = 0, },
			{ text = "10 percent", help = "10 percent", key = 10, },
			{ text = "15 percent", help = "15 percent", key = 15, },
			{ text = "20 percent", help = "20 percent", key = 20, },
			{ text = "30 percent", help = "30 percent", key = 30, },
			{ text = "40 percent", help = "40 percent", key = 40, },
			{ text = "50 percent", help = "50 percent", key = 50, },
			{ text = "75 percent", help = "75 percent", key = 75, },
			{ text = "100 percent", help = "100 percent", key = 100, },
			{ text = "200 percent", help = "200 percent", key = 200, },
			{ text = "over 9000 percent", help = "You know you want it", key = 9001, },
		},
	},
	{
		default = 1,
		label = "Survival: All Factions",
		help = "When enabled, each player get extra engineers or ACUs",
		key = 'opt_CenterAllFactions',
		pref = 'opt_CenterAllFactions',
		values = {
			{ text = "Disabled", help = "No extra units", key = 0, },
			{ text = "Enabled - engineers", help = "Each player gets 3 extra T1 engies", key = 1, },
			{ text = "Enabled - ACUs", help = "Each player gets 3 extra ACUs", key = 2, },
		}
	}
};